---
AWSTemplateFormatVersion: "2010-09-09"
Description: |
  A security stack containing IAM Role, policies, kms key,
  security groups etc
Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
    ConstraintDescription: Choose either dev or prod
  ProjectName:
    Type: String
    Description: Represents the project name
    Default: static-web-hosting
  Owner:
    Type: String
    Description: Represents the owner of the project
    Default: devOps
  ManagedBy:
    Type: String
    Description: Represents the IAC used
    Default: CloudFormation
  APPEC2Role:
    Type: String
    Description: |
      Represents the name associated to an IAM Role attached to the
      EC2 instance
    AllowedPattern: ^[\w+=,.@-]+$
  KeyAlias:
    Type: String
    Description: Represents the alias for the KMS key
    AllowedPattern: ^(alias/)[a-zA-Z0-9:/_-]+$
  EC2CloudWatchPolicyName:
    Type: String
    Description: Represents the name of the policy document of cloudwatch policy
    AllowedPattern: ^[\w+=,.@-]+$
  EC2BktAccessPolicyName:
    Type: String
    Description: Represents the name of the policy document of bkt access policy
    AllowedPattern: ^[\w+=,.@-]+$
  PurposeOfCloudInitLogGrp:
    Type: String
    Description: |
      Represents the purpose of the log group for cloud init level logs
    AllowedPattern: ^[A-Za-z0-9]+$
    Default: infrastructure
  ComponentOfCloudInitLogGrp:
    Type: String
    Description: Represents the component of the log group for system level logs
    AllowedPattern: ^[-A-Za-z0-9]+$
    Default: ec2
  NameOfCloudInitLogGrp:
    Type: String
    Description: Represents the name of the log group for system level logs
    AllowedPattern: ^[-A-Za-z0-9]+$
    Default: cloud-init
  PurposeOfSystemLogGrp:
    Type: String
    Description: Represents the purpose of the log group for system level logs
    AllowedPattern: ^[A-Za-z0-9]+$
    Default: infrastructure
  ComponentOfSystemLogGrp:
    Type: String
    Description: Represents the component of the log group for system level logs
    AllowedPattern: ^[-A-Za-z0-9]+$
    Default: ec2
  NameOfSystemLogGrp:
    Type: String
    Description: Represents the name of the log group for system level logs
    AllowedPattern: ^[-A-Za-z0-9]+$
    Default: system
Resources:
  CloudInitLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupClass: STANDARD
      LogGroupName: !Sub "${PurposeOfCloudInitLogGrp}/${ComponentOfCloudInitLogGrp}/${NameOfCloudInitLogGrp}"
      RetentionInDays: 7
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-cloud-init-log-grp"
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: !Ref ManagedBy
        - Key: Owner
          Value: !Ref Owner
  SystemLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupClass: STANDARD
      LogGroupName: !Sub "${PurposeOfSystemLogGrp}/${ComponentOfSystemLogGrp}/${NameOfSystemLogGrp}"
      RetentionInDays: 7
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-system-log-grp"
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: !Ref ManagedBy
        - Key: Owner
          Value: !Ref Owner
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
  EC2IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: |
        Provides access to read the S3 bucket, SSM access forinstance
        access, write logs to cloudwatch
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      RoleName: !Sub '${APPEC2Role}-${AWS::StackName}'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: !Ref ManagedBy
        - Key: Owner
          Value: !Ref Owner
  EC2CloudWatchPolicy:
    Type: AWS::IAM::RolePolicy
    Properties:
      PolicyName: !Ref EC2CloudWatchPolicyName
      RoleName: !Ref EC2IAMRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DescribeLogStreams
            Resource:
              - !Sub
                - '${CloudInitARN}:*'
                - {CloudInitARN: !GetAtt CloudInitLogGroup.Arn}
              - !Sub
                - '${SystemLogGrpARN}:*'
                - {SystemLogGrpARN: !GetAtt SystemLogGroup.Arn}
  EC2BktAccessPolicy:
    Type: AWS::IAM::RolePolicy
    Properties:
      PolicyName: !Ref EC2BktAccessPolicyName
      RoleName: !Ref EC2IAMRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:ListBucket
            Resource:
              - Fn::ImportValue:
                  Fn::Sub: "${Environment}-storage-artifact-bkt-arn"
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource:
              - !Join
                - ""
                - - Fn::ImportValue:
                      Fn::Sub: "${Environment}-storage-artifact-bkt-arn"
                  - "/*"
  AppInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2IAMRole
      InstanceProfileName: !Sub '${APPEC2Role}-${AWS::StackName}'
  EBSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS key for encrypting the EBS volumes
      Enabled: true
      KeySpec: SYMMETRIC_DEFAULT
      KeyPolicy:
        Version: 2012-10-17
        Id: key-policy-for-ebs-encryption
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Access for services
            Effect: Allow
            Principal:
              AWS: !GetAtt EC2IAMRole.Arn
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
            Resource: '*'
      KeyUsage: ENCRYPT_DECRYPT
      EnableKeyRotation: true
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-${ProjectName}-kms-key"
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Owner
          Value: !Ref Owner
        - Key: ManagedBy
          Value: !Ref ManagedBy
  EBSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Ref KeyAlias
      TargetKeyId: !Ref EBSKey
Outputs:
  EC2Role:
    Value: !Ref EC2IAMRole
    Description: Represents the IAM Role name
    Export:
      Name: !Sub "${Environment}-security-ec2-role"
  EC2RoleARN:
    Value: !GetAtt EC2IAMRole.Arn
    Description: Represents the IAM Role ARN
    Export:
      Name: !Sub "${Environment}-security-ec2-role-arn"
  IProfileName:
    Value: !Ref AppInstanceProfile
    Description: Represents the IAM Instance profile name
    Export:
      Name: !Sub "${Environment}-security-instance-profile"
  KMSKeyARN:
    Value: !GetAtt EBSKey.Arn
    Description: Represents the ARN of the KMS key
    Export:
      Name: !Sub "${Environment}-security-kms-key-arn"