name: Application Infrastructure Pipeline

on:
  push:
    paths:
      - 'infra/launch_template/**'
      - 'infra/application/**'
      - '.github/workflows/deploy-app-infra.yaml'
    branches:
      - dev
      - prod

  workflow_dispatch:

concurrency:
  group: platform-deploy
  cancel-in-progress: false

env:
  AWS_REGION: ${{ github.ref == 'refs/heads/prod' && 'us-east-1' || 'us-east-2' }}
  ENVIRONMENT: ${{ github.ref == 'refs/heads/prod' && 'prod' || 'dev'}}

jobs:
  detect_changes:
    runs-on: ubuntu-latest

    outputs:
      lt_changed: ${{ steps.filter.outputs.lt }}
      app_changed: ${{ steps.filter.outputs.app }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Detect changes
        id: filter
        uses: dorny/paths-filter@v4
        with:
          filters: |
            lt:
              - 'infra/launch_template/**'
            app:
              - 'infra/application/**'

  deploy-lt:
    runs-on: ubuntu-latest
    needs: detect_changes
    if: needs.detect_changes.outputs.lt_changed == 'true'

    permissions:
      id-token: write
      contents: read

    env:
      DEV_EXECUTION_ROLE_ARN: ${{ secrets.DEV_APP_INFRA_EXECUTION_ROLE_ARN }}
      PROD_EXECUTION_ROLE_ARN: ${{ secrets.PROD_APP_INFRA_EXECUTION_ROLE_ARN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Configure AWS credentials for dev
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: ${{ github.ref == 'refs/heads/dev' && secrets.DEV_APP_INFRA_DEPLOY_ROLE_ARN || secrets.PROD_APP_INFRA_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Set stack
        run: |
          echo "STACK=launch-template" >> "${GITHUB_ENV}"

      - name: Set runtime file path
        run: |
          echo "RUNTIME_FILE=infra/launch-template/runtime-${ENVIRONMENT}.json" >> $GITHUB_ENV

      - name: Generate runtime parameter file
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)

          jq --arg sha "$SHORT_SHA" '
            map(
              if .ParameterKey == "BootstrapVersion"
              then .ParameterValue = $sha
              else .
              end
            )
          ' infra/launch-template/${ENVIRONMENT}.json > "${RUNTIME_FILE}"

      - name: Deploy stack
        run: |
          set -e

          echo "=================================================================="
          echo "============= Processing stack: ${ENVIRONMENT}-${STACK}-stack =============="
          echo "=================================================================="

          TEMPLATE_FILE="infra/${STACK}/${STACK}-stack.yaml"

          echo "-> Running yamllint..."
          yamllint $TEMPLATE_FILE

          echo "-> Running cfn-lint..."
          cfn-lint $TEMPLATE_FILE

          echo "-> Validating CloudFormation template..."
          aws cloudformation validate-template --template-body file://$TEMPLATE_FILE

          STACK_NAME="${ENVIRONMENT}-${STACK}-stack"

          if [[ "${ENVIRONMENT}" == "dev" ]]; then
            ROLE_ARN="${DEV_EXECUTION_ROLE_ARN}"
          else
            ROLE_ARN="${PROD_EXECUTION_ROLE_ARN}"
          fi

          echo "ROLE_ARN=${ROLE_ARN##*/}"

          aws cloudformation deploy \
            --stack-name "${STACK_NAME}" \
            --template-file "${TEMPLATE_FILE}" \
            --parameter-overrides file://"${RUNTIME_FILE}" \
            --capabilities CAPABILITY_NAMED_IAM \
            --role-arn "${ROLE_ARN}" \
            --region "${AWS_REGION}" \
            --debug

      - name: Cleanup runtime parameter file
        if: always()
        run: |
          rm -f ${RUNTIME_FILE}

  deploy-app:
    runs-on: ubuntu-latest
    needs: [detect_changes, deploy-lt]

    if: needs.detect_changes.outputs.lt_changed == 'true' || needs.detect_changes.outputs.app_changed

    permissions:
      id-token: write
      contents: read

    env:
      DEV_EXECUTION_ROLE_ARN: ${{ secrets.DEV_APP_INFRA_EXECUTION_ROLE_ARN }}
      PROD_EXECUTION_ROLE_ARN: ${{ secrets.PROD_APP_INFRA_EXECUTION_ROLE_ARN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Configure AWS credentials for dev
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: ${{ github.ref == 'refs/heads/dev' && secrets.DEV_APP_INFRA_DEPLOY_ROLE_ARN || secrets.PROD_APP_INFRA_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Set stack
        run: |
          echo "STACK=application" >> "${GITHUB_ENV}"

      - name: Deploy stack
        run: |
          set -e

          echo "=================================================================="
          echo "============= Processing stack: ${ENVIRONMENT}-${STACK}-stack =============="
          echo "=================================================================="

          TEMPLATE_FILE="infra/${STACK}/${STACK}-stack.yaml"
          PARAMS_FILE="infra/${STACK}/${ENVIRONMENT}.json"
            
          echo "-> Running yamllint..."
          yamllint $TEMPLATE_FILE

          echo "-> Running cfn-lint..."
          cfn-lint $TEMPLATE_FILE

          echo "-> Validating CloudFormation template..."
          aws cloudformation validate-template --template-body file://$TEMPLATE_FILE

          STACK_NAME="${ENVIRONMENT}-${STACK}-stack"

          if [[ "${ENVIRONMENT}" == "dev" ]]; then
            ROLE_ARN="${DEV_EXECUTION_ROLE_ARN}"
          else
            ROLE_ARN="${PROD_EXECUTION_ROLE_ARN}"
          fi

          echo "ROLE_ARN=${ROLE_ARN##*/}"

          aws cloudformation deploy \
            --stack-name "${STACK_NAME}" \
            --template-file "${TEMPLATE_FILE}" \
            --parameter-overrides file://"${PARAMS_FILE}" \
            --capabilities CAPABILITY_NAMED_IAM \
            --role-arn "${ROLE_ARN}" \
            --region "${AWS_REGION}" \
            --debug