name: Infra Deployment

on:
  push:
    paths:
      - 'infra/**'
    branches:
      - dev
      - prod

jobs:
  deploy-infra:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ github.ref == 'refs/heads/dev' && 'us-east-2' || github.ref == 'refs/heads/prod' && 'us-east-1' }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set ENV based on branch
        run: |
          if [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            echo "ENV=dev" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "prod" ]]; then
            echo "ENV=prod" >> $GITHUB_ENV
          else
            echo "ENV=unknown" >> $GITHUB_ENV
          fi

      - name: Resetting infra deployment status
        run: |
          aws ssm put-parameter \
            --name "/${ENV}/static-web-infra-ready" \
            --value "false" \
            --type String \
            --overwrite \
            --region $AWS_REGION

      - name: Set stack order
        id: stacks
        run: echo "STACKS=storage security network application" >> $GITHUB_ENV

      - name: Validate and deploy stacks
        run: |
          for STACK in $STACKS; do
            echo "==== Processing stack: $ENV-$STACK-stack ===="

            TEMPLATE_FILE="infra/$STACK/$STACK-stack.yaml"
            PARAMS_FILE="infra/$STACK/${{ github.ref == 'refs/heads/dev' && 'dev.json' || 'prod.json' }}"

            echo "-> Running yamllint..."
            yamllint $TEMPLATE_FILE

            echo "-> Running cfn-lint..."
            cfn-lint $TEMPLATE_FILE

            echo "-> Validating CloudFormation template..."
            aws cloudformation validate-template --template-body file://$TEMPLATE_FILE

            STACK_NAME="${ENV}-${STACK}-stack"

            aws cloudformation deploy \
              --stack-name "$STACK_NAME" \
              --template-file "$TEMPLATE_FILE" \
              --parameter-overrides file://"$PARAMS_FILE" \
              --capabilities CAPABILITY_NAMED_IAM \
              --region "$AWS_REGION"
          done

      - name: Update storage ssm parameter
        run: |
          STACK="${ENV}-storage-stack"
          BUCKET_NAME=$(aws cloudformation describe-stacks \
            --stack-name "$STACK" \
            --query "Stacks[0].Outputs[?OutputKey=='OutputBktName'].OutputValue" \
            --output text \
            --region "$AWS_REGION")

          if [ -z "$BUCKET_NAME" ]; then
            echo "BucketName output missing"
            exit 1
          fi

          aws ssm put-parameter \
            --name "${ENV}/${{ vars.SSM_BUCKET_PARAM }}" \
            --value "$BUCKET_NAME" \
            --type String \
            --overwrite \
            --region "$AWS_REGION"
          echo "Stored $BUCKET_NAME in SSM"

      - name: Update app ssm parameter
        run: |
          STACK="${ENV}-application-stack"
          ALB_DNS=$(aws cloudformation describe-stacks \
            --stack-name "$STACK" \
            --query "Stacks[0].Outputs[?OutputKey=='ALBPublicDNS'].OutputValue" \
            --output text \
            --region "$AWS_REGION")

          if [ -z "$ALB_DNS" ]; then
            echo "ALB DNS output missing"
            exit 1
          fi

          aws ssm put-parameter \
            --name "${ENV}/${{ vars.SSM_ALB_DNS_PARAM }}" \
            --value "$ALB_DNS" \
            --type String \
            --overwrite \
            --region "$AWS_REGION"
          echo "Stored $ALB_DNS in SSM"

      - name: Verify stack statuses
        run: |
          for STACK in $STACKS; do
            STACK_NAME = $ENV-$STACK-stack
            STATUS=$(aws cloudformation describe-stacks \
              --stack-name $STACK_NAME \
              --region ${{ env.AWS_REGION }} \
              --query "Stacks[0].StackStatus" \
              --output text)
            echo "$STACK_NAME status: $STATUS"
            if [[ "$STATUS" != "CREATE_COMPLETE" && "$STATUS" != "UPDATE_COMPLETE" ]]; then
              echo "Error: $STACK_NAME stack deployment failed"
              exit 1
            fi
          done

      - name: Setting infra deployment status
        run: |
          aws ssm put-parameter \
            --name "/${ENV}/static-web-infra-ready" \
            --value "true" \
            --type String \
            --overwrite \
            --region $AWS_REGION
