name: Golden Image Pipeline

on:
  push:
    branches:
      - dev
      - prod
    paths:
      - 'packer/**'

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment tier
        id: env
        run: echo "env_tier=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
