name: Infra Validation

on:
  pull_request:
    paths:
      - 'infra/**'
    branches:
      - dev
      - prod

jobs:
  validate-infra:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ github.base_ref == 'dev' && 'us-east-2' || github.base_ref == 'prod' && 'us-east-1' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set stack order
        id: stacks
        run: echo "STACKS=storage security network application" >> $GITHUB_ENV

      - name: Validate and deploy stacks
        run: |
          for STACK in $STACKS; do
            echo "==== Processing stack: $STACK-stack ===="

            TEMPLATE_FILE="infra/$STACK/$STACK-stack.yaml"
            PARAMS_FILE="infra/$STACK/${{ github.ref == 'refs/heads/dev' && 'dev.json' || 'prod.json' }}"

            echo "-> Running yamllint..."
            yamllint $TEMPLATE_FILE

            echo "-> Running cfn-lint..."
            cfn-lint $TEMPLATE_FILE

            echo "-> Validating CloudFormation template..."
            aws cloudformation validate-template --template-body file://$TEMPLATE_FILE
          done