name: IAC Validation Pipeline

on:
  pull_request:
    paths:
      - 'infra/**'
    branches:
      - dev
      - prod

jobs:
  validate-infra:
    runs-on: ubuntu-latest

    permissions: 
      id-token: write
      contents: read

    env:
      AWS_REGION: ${{ github.base_ref == 'dev' && 'us-east-2' || github.base_ref == 'prod' && 'us-east-1' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.VALIDATION_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set stack order
        id: stacks
        run: echo "STACKS=storage network security" >> $GITHUB_ENV

      - name: Validate and deploy stacks
        run: |
          set -e

          for STACK in $STACKS; do
            echo "==== Processing stack: $STACK-stack ===="

            TEMPLATE_FILE="infra/$STACK/$STACK-stack.yaml"

            echo "-> Running yamllint..."
            yamllint $TEMPLATE_FILE

            echo "-> Running cfn-lint..."
            cfn-lint $TEMPLATE_FILE

            echo "-> Running cloudformation validate..."
            aws cloudformation validate-template \
              --template-body file://$TEMPLATE_FILE

          done